name: CMake

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          install-deps: |
            sudo apt-get update -y
            sudo apt-get install -y xorg-dev
        
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - if: ${{ matrix.install-deps }}
      name: Install dependencies
      run: ${{ matrix.install-deps }}

    - name: Configure CMake
      run: cmake -S examples -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
